remote_theme: mmistakes/so-simple-theme
locale: en-US
title: "Genomics and Environmental Research in Microbial Systems"
description: ""
baseurl: "" # the subpath of your site, e.g. "/blog"
url:  "www.germslab.org" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: "/images/GB-LOGO-RGB_MAIN-STACKED.svg" # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: # reading time estimates, e.g. true
words_per_minute: # 200
mathjax: # MathJax equations, e.g. true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: UA-39200706-2 # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: teeniedeenie # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomoy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-github-metadata

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name: Adina Howe
  picture:
  email: adina@iastate.edu
  twitter: teeniedeenie
  links:
    - title:
      url:
      icon:

# Collections
collections:
  research:
    output: true
    permalink: /:collection/:path/
  photo_gallery:
    output: true


# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Research defaults
  - scope:
      path: "_research"
      type: research
    values:
      layout: post
      comments: false
      share: true

# Footer Links
#footer_links:
#  - title: Feed
#    url: atom.xml
#    icon: fas fa-rss-square
